api:
  build: backend
  environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_USER=wiki
    - POSTGRES_PASSWORD=notasecret
    - NODE_ENV=development
  expose:
    - 3000
  links:
    - postgres
web:
  build: web
  ports:
    - 8000:80
  links:
    - api
  volumes:
    - ./web/foo:/usr/share/nginx/beacon:ro
    - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./web/nginx/sites-available:/etc/nginx/sites-available
postgres_data:
  image: postgres:9.4.5
  entrypoint: /bin/bash
postgres:
  image: postgres:9.4.5
  environment:
    - POSTGRES_DB=wiki
    - POSTGRES_USER=wiki
    - POSTGRES_PASSWORD=notasecret
  volumes_from:
    - postgres_data
