postgres_data:
  image: postgres:9.4.5
  entrypoint: /bin/bash
postgres:
  image: postgres:9.4.5
  environment:
    - POSTGRES_DB=wiki
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_USER=postgres
  volumes_from:
    - postgres_data
api:
  build: backend
  environment:
    - NODE_ENV=production
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_USER=postgres
  expose:
    - 3000
  links:
   - postgres
web:
  build: web
  ports:
    - 8000:80
  links:
    - api
