postgres_data:
  image: postgres:9.4.5
  entrypoint: /bin/bash
postgres:
  image: postgres:9.4.5
  environment:
    - POSTGRES_DB=wiki
    - POSTGRES_PASSWORD=changeit
    - POSTGRES_USER=postgres
  volumes_from:
    - postgres_data
api:
  image: food-forest/api:latest
  ports:
    - "8080"
  links:
    - postgres
web:
  build: web
  ports:
    - "8000:80"
  links:
    - api
  volumes:
    - ../dist:/usr/share/nginx/foodforest:ro
